_target_: src.models.beta_vae.BetaVAE

encoder:
  _target_: src.architectures.mlp.MLPEncoder
  input_dim: 2
  hidden_dims: [2048]

decoder:
  _target_: src.architectures.mlp.MLPDecoder
  input_dim: 2
  hidden_dims: [2048]
  output_dim: 2

latent_dim: 2
beta: 1
lr: 1e-4
