_target_: src.models.diffusion.Diffusion
denoiser:
  _target_: src.architectures.mlp.MLPVelocityField
  data_dim: ${..data_dim}
  hidden_dims: [256, 256]
  time_embed_dim: 32
  activation: ReLU
  skip_connection: true
data_dim: ???
noise_schedule: vp_cosine
prediction_type: epsilon
sampler: ddim
schedule_kwargs: null
n_sampling_steps: 100
lr: 2e-3
