_target_: src.models.diffusion.Diffusion
architecture:
  type: mlp
  hidden_dims: [256, 256]
  time_embed_dim: 32
  activation: ReLU
data_dim: ???
noise_schedule: vp_cosine
prediction_type: epsilon
sampler: ddim
schedule_kwargs: null
n_sampling_steps: 100
lr: 2e-3
