_target_: src.models.ebm.EBM
data_dim: ???
lr: 1e-4
langevin_steps: 60
langevin_step_size: 0.01
langevin_noise_scale: 0.005
grad_clamp: 0.03
replay_buffer_size: 10000
replay_prob: 0.95
energy_reg_weight: 1.0
init_range: 2.0
