_target_: src.models.flow_matching.FlowMatching
architecture:
  type: mlp
  hidden_dims: [256, 256, 256]
  time_embed_dim: 32
  activation: ReLU
data_dim: ???
sigma_min: 0.0
n_sampling_steps: 100
lr: 2e-3
