_target_: src.models.beta_vae.IWAE

encoder:
  _target_: src.architectures.mlp.MLPEncoder
  input_dim: 2
  hidden_dims: [2048, 256]

decoder:
  _target_: src.architectures.mlp.MLPDecoder
  input_dim: ${..latent_dim}
  hidden_dims: [256, 2048]
  output_dim: 2

latent_dim: 2
k: 5
lr: 2e-3
