_target_: src.models.beta_vae.BetaVAE

data_dim: ???

encoder:
  _target_: src.architectures.mlp.MLPEncoder
  input_dim: ${..data_dim}
  hidden_dims: [2048, 256]
  activation: ReLU

decoder:
  _target_: src.architectures.mlp.MLPDecoder
  input_dim: ${..latent_dim}
  hidden_dims: [256, 2048]
  output_dim: ${..data_dim}
  activation: ReLU

latent_dim: 2
beta: 1
lr: 2e-3
