defaults:
  - /data: moons
  - /model: ebm
  - /architecture: mlp
  - /trainer: default
  - /evaluate: default
  - /logger: wandb
  - /callbacks: default
  - override hydra/launcher: submitit_slurm
  - _self_

seed: 42
ckpt_path: null
