# conf/hydra/launcher/submitit_slurm.yaml
# @package hydra.launcher

_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
submitit_folder: ${hydra.sweep.dir}/.submitit
name: ${hydra.job.name}

timeout_min: 45
cpus_per_task: 2
tasks_per_node: 1
nodes: 1
mem_gb: 4
array_parallelism: 16

additional_parameters:
  # comment: "preemption=yes;requeue=yes"
  account: torch_pr_147_courant
  # gres: gpu:1
