# @package hydra.launcher
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 120
cpus_per_task: 4
gpus_per_node: 1
tasks_per_node: 1
mem_gb: 16
nodes: 1
name: ${hydra.job.name}
partition: null
