defaults:
  - /data: spiral
  - /model: diffusion
  - /architecture: resmlp
  - /trainer: default
  - /logger: wandb
  - /callbacks: default
  - override /hydra/launcher: submitit_slurm
  - _self_

seed: 42
ckpt_path: null
n_samples: 1000

model:
  lr: 3e-4
